### ISSUE TITLE
[建议]把紫皮归类到2星，然后把金皮归类到3星，改造根据改造后的颜色归类？

### ISSUE THREAD

**Issue by foxwhite25** [HMScygnet/_blhx_data#2]
不知道你解包的方法允不允许这样的操作，但是现在这样3星真的很少，而1,2星就太多了
![0)Z2 }BNI87~90HYZF `H6](https://user-images.githubusercontent.com/39846845/106193705-d5128600-61e8-11eb-8ece-8b1c90b3e10e.PNG)
我原本的爬虫就是按这样爬的，效果看起来还不错

**Comment by HMScygnet** [comment]
编号是手动编号，与解包无关。这个数据是为碧蓝航线版戳一戳创立的，所以有意将三星数量控制的很少，如果有其他用途的话可以自行修改编号
