### ISSUE TITLE
会继续更新吗

### ISSUE THREAD

**Issue by SlightDust** [HMScygnet/_blhx_data#4]
大佬这个还会继续更新吗，或者想知道图片来源。

**Comment by HMScygnet** [comment]
在更了在更了，三天内更新，图片来源是游戏内解包

**Comment by SlightDust** [comment]
好耶！

**Comment by SlightDust** [comment]
![GDFL7GNU9UE)G~OU2DZ$W 0](https://user-images.githubusercontent.com/53001305/170504802-44ef4693-5648-4517-b65c-f17ef2871208.jpg)
